language: python
python:
  - "2.7"
# command to install dependencies
install:
 - pip install -r requirements.txt
 - "pip install https://github.com/hudsonbrendon/pyeventick/archive/master.zip"

# command to run tests
script: ./runtests
